### ISSUE TITLE
Error after editing data

### ISSUE THREAD

**Issue by Azathoth2k** [Kevin-OConnor/PiScout-2016#33]
After trying to edit data, piscout.py throws an error about the data format. 
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\matplotlib\cbook\__init__.py", line 389, in process
    proxy(*args, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\matplotlib\cbook\__init__.py", line 227, in __call__
    return mtd(*args, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\matplotlib\widgets.py", line 230, in _release
    func(event)
  File "piscout.py", line 328, in edit
    self.submit()
  File "piscout.py", line 215, in submit
    if self.data['Team'] == 0:

 It looks like the code only assembles the data but does not create a dictionary

This is the final output from piscout.py  before sending the data back to be redisplayed
[123, 2, 75, 0, 0, 0, 0, 0, 0, 0, 0, 1, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 
current code
 d.append(int(line.split('=')[1].replace('\n', '')))
 self.data=d

I am new to Python so I hacked together the following workaround 

 f1,f2=line.split("=")
 f3=int(f2.replace('\n', ''))
self.data[f1]=f3

**Comment by Kevin-OConnor** [comment]
Thanks for the feedback! It looks like this code was not properly updated when the internal data storage switched from a list to a dict. Your fix looks like it may work, but I would rather clean the code up further by just writing and reading JSON. I will push a fix shortly.
